---
title: "lab-07-pt2"
author: "Grant Matthai"
date: "2024-03-06"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here is a simple chunk of code: 

```{r}
names <- c("John", "Emily", "Michael", "Sophia", "William", "Olivia", "James", "Emma", "Benjamin", "Ava")

ages <- c(32, 28, 35, 30, 40, 50, 39, 33, 37, 29)

careers <- c("Engineer", "Teacher", "Doctor", "Artist", "Accountant", "Professor", "Nurse", "Writer", "Lawyer", "Chef")

df <- data.frame("Names" = names, "Age" = ages, "Career" = careers)
df
```

Here is a simple chunk of code created in GitHub: 

```{r}
names2 <- c("Eleanor", "Simon", "Clara", "Theodore", "Violet", "Oscar", "Julia", "Nathan", "Alice", "Henry")

ages2 <- c(32, 45, 28, 35, 40, 27, 39, 41, 33, 36)

careers2 <- c("Ethical Hacker", "Artisanal Baker", "Astrobiologist", "Cryptocurrency Analyst", "Data Ethicist", "Nanotechnologist", "Quantum Physicist", "Futurist", "Space Tourism Guide", "Virtual Reality Designer")

df2 <- data.frame("Names" = names2, "Age" = ages2, "Career" = careers2)
df2
```
